from = "sender@example.org"
to = "recipient@example.net"
subject = "Let It Be"
attachFile = "./test/attach.png"
contentType = "text/html"
body = '''<h1>When I find myself in times of trouble
Mother Mary comes to me
Speaking words of wisdom, let it be
And in my hour of darkness
She is standing right in front of me
Speaking words of wisdom, let it be
Let it be, let it be
Let it be, let it be
Whisper words of wisdom, let it be</h1>
'''

[smtp]
user = "account@gmail.com"
pwd = "gmail password"
host = "smtp.gmail.com"
port = "587"

